#helm:generate helm tpl -d values.toml -o manifests/drone-proxy-rc.yaml $HELM_GENERATE_FILE
apiVersion: v1
kind: ReplicationController
metadata:
  name: drone-proxy
  labels:
    heritage: helm
spec:
  replicas: 1
  selector:
    name: drone-proxy
  template:
    metadata:
      labels:
        name: drone-proxy
    spec:
      containers:
        - image: abiosoft/caddy:latest
          name: drone-proxy
          command:
            - "caddy"
            - "--conf"
            - /etc/caddy/caddy.conf
            - "--email"
            - "{{ .web.letsencrypt_email }}"
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
            - name: https
              containerPort: 443
              protocol: TCP
          volumeMounts:
            - mountPath: /etc/caddy
              name: config-volume
      volumes:
        - name: config-volume
          configMap:
            name: drone
