#helm:generate helm tpl -d values.toml -o manifests/drone-server-rc.yaml $HELM_GENERATE_FILE
apiVersion: v1
kind: ReplicationController
metadata:
  name: drone-server
  labels:
    heritage: helm
spec:
  replicas: 1
  selector:
    name: drone-server
  template:
    metadata:
      labels:
        name: drone-server
    spec:
      containers:
        - image: drone/drone:0.4
          name: drone-server
          env:
            # HTTP Listen Address
            - name: SERVER_ADDR
              value: ":80"
            # DB stuff
            - name: DATABASE_DRIVER
              value: sqlite3
            # This ends up being a mounted Google Cloud Disk.
            - name: DATABASE_CONFIG
              value: /var/lib/drone/drone.sqlite
            # RCS stuff
            - name: REMOTE_DRIVER
              value: {{ .remote.driver }}
            - name: REMOTE_CONFIG
              value: {{ .remote.config }}
          ports:
            - containerPort: 80
              protocol: TCP
          volumeMounts:
            # Persist our configs in an SQLite DB in here
#            - mountPath: /var/lib/drone
#              name: drone-server-sqlite-db
            # Enables Docker in Docker
            - mountPath: /var/run/docker.sock
              name: docker-socket
            - mountPath: /var/lib/docker
              name: docker-lib
      volumes:
#        - name: drone-server-sqlite-db
#          gcePersistentDisk:
#            pdName: drone-server-sqlite-db
#            fsType: ext4
        - name: docker-socket
          hostPath:
            path: /var/run/docker.sock
        - name: docker-lib
          hostPath:
            path: /var/lib/docker